### ISSUE TITLE
[FEATURE] Create a .devcontainer config to enable a one-click local development environment

### ISSUE THREAD

**Issue by disposedtrolley** [omshub/website#12]
Creating a [devcontainer](https://code.visualstudio.com/docs/remote/containers) config would allow VSCode users the ability to instantly spin up a local development environment via Docker, with all dependencies (like NodeJS, yarn, and stuff we'll add in the future) installed and ready to go.

Devcontainers can be executed locally and also on [Codespaces](https://docs.github.com/en/codespaces).

**Comment by awpala** [comment]
+1 vote for this suggestion, I loooove Docker, personally

**Comment by disposedtrolley** [comment]
I'll try and carve out a PR after work today!
