### ISSUE TITLE
[BUG] Inconsistent color mapping in averages on `[courseid]`

### ISSUE THREAD

**Issue by awpala** [omshub/website#134]
**Describe the bug**
Color mapping seems to be applied inconsistently for the averages on `[courseid]`.

**To Reproduce**
Representative examples:
- https://www.omshub.org/course/CS-6603 (no colors applied)
- https://www.omshub.org/course/CS-6675 (color only applied to avg difficulty)
- https://www.omshub.org/course/CS-6290 (no colors applied)

**Expected behavior**
Follow the color mapping exactly / fix associated bug in mapping logic.

**Additional context**
(N/A)

**Comment by austinoboyle** [comment]
I'll grab this to get my feet wet

**Comment by omshub-admin** [comment]
> I'll grab this to get my feet wet

Good call! This would be a good one to get generally oriented with the current setup and such, and a good value-add to fix in the near term to boot!
