### ISSUE TITLE
[FEATURE] Add sponsorship button on github repo

### ISSUE THREAD

**Issue by ctran4347** [omshub/website#14]
I think this will be useful later on as we get the website going and might need help with funding!

**Comment by awpala** [comment]
I think financial transparency will be a key feature down the road once we hit critical mass and MVP/steady state, I'm even up for adding some kind of widget on the frontpage or somewhere conspicuous detailing real-time expenses vs. revenue, for full transparency to the users

**Comment by awpala** [comment]
We are currently operating at near-zero cost, and intend to do so for the foreseeable future. If future needs change this, we can revisit at the appropriate time accordingly.
