### ISSUE TITLE
[FEATURE] Commenting on reviews for discussion

### ISSUE THREAD

**Issue by driscoll42** [omshub/website#16]
**Is your feature request related to a problem? Please describe.**
Reviews are given with not discussion

**Describe the solution you'd like**
Allow for commenting on reviews to have discussion on what is in a review.

**Describe alternatives you've considered**
This may encourage some trolling, or useless chatter. I feel we would need to enable notifications to the reviewer to let them know about a comment.

**Additional context**
N/A

**Comment by CBlumini** [comment]
Would we need a moderation team to make this feature "safe" for the users?

**Comment by driscoll42** [comment]
I think you're definitely right, and I imagine such a moderation group would be difficult to manage/maintain which would be enough reason to me at least to push this to the bottom of the backlog if not just reject entirely. Though it does make me think there should be an ability to "report" a review in case a review is violating the ToS, e.g. Derogatory language, includes content a professor has requested not be shared, etc...

**Comment by awpala** [comment]
I think an upvote/downvote system Will have a larger immediate impact / "wow factor," but a discussion section could be something users end up requesting...trolling is definitely a concern, wouldn't want the platform to devolve into the bad parts of Reddit

**Comment by CBlumini** [comment]
> I think you're definitely right, and I imagine such a moderation group would be difficult to manage/maintain which would be enough reason to me at least to push this to the bottom of the backlog if not just reject entirely. Though it does make me think there should be an ability to "report" a review in case a review is violating the ToS, e.g. Derogatory language, includes content a professor has requested not be shared, etc...

I think being able to report could be a decent compromise. That would also help deal with stuff like double posts, stuff intentionally trying to skew the data etc

**Comment by awpala** [comment]
Closing as stale (i.e., lack of interest, ability to develop with current-to-long-term resources, etc.). Please reopen with appropriate justification if still relevant.
