### ISSUE TITLE
[FEATURE] Wordclouds

### ISSUE THREAD

**Issue by driscoll42** [omshub/website#18]
**Is your feature request related to a problem? Please describe.**
There can be hundreds of reviews and hard to pull out themes of the reviews

**Describe the solution you'd like**
A wordcloud of the content of the reviews could be interesting to see what stands out in the reviews

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by CBlumini** [comment]
This is something that would be a really cool enhancement. I'd be very interested in working on this one once we get to the point of building this up.

**Comment by awpala** [comment]
Closing as stale (i.e., lack of interest, ability to develop with current-to-long-term resources, etc.). Please reopen with appropriate justification if still relevant.
