### ISSUE TITLE
[DISCUSSION] Ensure compatibility/information with OMSA/OMSCY

### ISSUE THREAD

**Issue by driscoll42** [omshub/website#19]
**Is your feature request related to a problem? Please describe.**
Generally OMSCentral was focused on OMSCS, and a new website should be inclusive of OMSA and OMSCY, see the MSCSHub and MSDSHub for examples. OMSA/OMSCY must have buy in to the site for it to be successful and part of conversations

**Comment by yktan89** [comment]
Hey @driscoll42, YK here - will be able to help out for OMSA.

**Comment by driscoll42** [comment]
This is really not a specific issue to be worked on, just something that needs to be kept in everyone's minds as we work on the site.

**Comment by awpala** [comment]
Closing as stale (i.e., lack of interest, ability to develop with current-to-long-term resources, etc.). Please reopen with appropriate justification if still relevant.
