### ISSUE TITLE
[INVESTIGATION] Explore similar websites for ideas

### ISSUE THREAD

**Issue by driscoll42** [omshub/website#20]
MSCSHub/MSDSHub should be investigated for what features to copy to a new site to make the site more useful, but without being too cluttered. After exploration new issues/feature requests should be made.

**Comment by knakamura13** [comment]
Rate My Professor has a decent design we could pull from.

https://www.ratemyprofessors.com/ShowRatings.jsp?tid=2638309

**Comment by driscoll42** [comment]
Good point, I kind of like the tags that could be added, maybe a list of a twenty predefined tags people could select at most 3-5 from? And the other info, just of course have to be careful about feature bloat.

**Comment by driscoll42** [comment]
![image](https://user-images.githubusercontent.com/4751505/167754127-f66a4c89-2b53-4a35-a0ce-a068d7ab086e.png)

Something kind of like that for the ML spec, very rough draft. Probably would want to pull in some other courses (e.g. CP helping CV I think) but for a concept

**Comment by premk** [comment]
Yes! This is what I meant.

**Comment by driscoll42** [comment]
For the course maps I made #30 and assigned myself to it. Still worth keeping this ticket open for other ideas to copy/steal.

**Comment by togogh** [comment]
Not really a course review site, but I like that we can filter according to reviewer type on agoda.com.

![image](https://user-images.githubusercontent.com/5388340/168422091-8c7fff38-f03b-4ddf-85fe-f7f798960909.png)

Like in this case, it's filtering for reviews from solo travelers only.

It would be nice to be able to filter between reviews from students of different programs in OMShub. As an OMSA student, I'll probably find reviews from OMSA students a lot more relevant to me.

Maybe have people fill out a basic profile when they create an account? Then they won't have to indicate what program they're from every time they make a review.

A keyword filter would be nice too, but will probably be much more complicated to implement.

![image](https://user-images.githubusercontent.com/5388340/168422217-4f435e8b-aea1-4b18-b16c-39a63ddbfd4a.png)

**Comment by driscoll42** [comment]
I was referred to https://osu-cs-course-explorer.com/ for more suggestions

**Comment by awpala** [comment]
Closing as stale (i.e., lack of interest, ability to develop with current-to-long-term resources, etc.). Please reopen with appropriate justification if still relevant.
