### ISSUE TITLE
[CORE FEATURE] Determine if possible to use OMSCentral Data

### ISSUE THREAD

**Issue by driscoll42** [omshub/website#22]
**Is your feature request related to a problem? Please describe.**
The site lives and dies by its data, and currently we would need to start from scratch, even OMSCentral started from a Google Doc originally so it had data.

**Describe the solution you'd like**
Need to determine two things, if we can use the data at all, and if Mehmet would allow us to get a database extract to load.

**Describe alternatives you've considered**
Start from nothing and build it.

**Additional context**
Lots of potential legal issues here and would have be very clear as what can be done.

**Comment by ilanbarshir** [comment]
I am suggesting to act as an 'hybrid aggregator'. You scrape from omscentral only the summary of the results (Do it daily), then show reviews written on this platform. Combine both scores in some logic

**Comment by MatthewCaseres** [comment]
We have the data and the issue can be closed? https://omscentral.com/assets/json/omscentral_reviews.json

**Comment by driscoll42** [comment]
This is not whether we have the data so much as the legality of using the data

**Comment by awpala** [comment]
Resolved. Data has been made public, and de facto not explicitly owned. Any future contentions of use by OMSHub will be handled/resolved as necessary at the appropriate time.
