### ISSUE TITLE
[ADMINSTRATIVE] Determine involvement with GA Tech

### ISSUE THREAD

**Issue by driscoll42** [omshub/website#24]
**Is your feature request related to a problem? Please describe.**
Ideally this site would be at least semi-officially supported by GA Tech, Dr. Joyner for example, possibly with funding support but at least approval. 

**Describe the solution you'd like**
Once MVP is basically done, have a discussion with Dr. Joyner about the future of the site and how this site could work with GA Tech.

**Comment by premk** [comment]
We can also ask for permission to use Gatech branding in our site. It is allowed for non-commercial use but we need to get permission first according to the [licensing guidelines](https://licensing.gatech.edu/faqs)

**Comment by premk** [comment]
I've created #31 to track the branding permission. We can reach out to the program director once #9 is closed.

**Comment by awpala** [comment]
We can run this in parallel with MVP development, they're not mutually blocking, but I think the sooner we get an idea, the better, in terms of how we roll out and operate in phase 2 / post-MVP

**Comment by awpala** [comment]
Leaving open for relevance, however, stating for record as of Aug 2022 that this will unlike be completed due to lack of resources / dedicated personnel. Based on current trajectory, scope of this project will be limited primarily to reviews functionality.

**Comment by awpala** [comment]
Closing as stale (i.e., lack of interest, ability to develop with current-to-long-term resources, etc.). Please reopen with appropriate justification if still relevant.
