### ISSUE TITLE
[DISCUSSION] Determine relationship or lack there of with OMSCentral

### ISSUE THREAD

**Issue by driscoll42** [omshub/website#25]
Similar to #22 a discussion should be had with Mehmet (possibly Martz too) about any collaboration, relationship, etc... with OMSCentral. It would be in the best interest of the community to have one site and not two and cannot emphasize enough the gratitude the community has for OMSCentral, but one that is community owned is probably best.

**Comment by MatthewCaseres** [comment]
OMSCentral is gone, right?

https://omscentral.com/

**Comment by awpala** [comment]
Closing for obsolescence. OMSCentral domain/IP has been transferred to [OMS Tech](https://github.com/oms-tech) org as of July 2022.
