### ISSUE TITLE
[CORE FEATURE] Transparent Funding

### ISSUE THREAD

**Issue by driscoll42** [omshub/website#26]
**Is your feature request related to a problem? Please describe.**
The core issue inspiring this site was the paywall going up on OMSCentral. 

**Describe the solution you'd like**
To inspire confidence in a new site by users, all financials related to the site should be transparent, costs, donations, etc... Probably a quarterly or yearly report on server costs, maintenance, etc... with how many people donated money.

**Comment by knakamura13** [comment]
This is a great idea. I wonder if it's worth setting up a dashboard that automatically updates with costs and donations, or if we should just manually update the site every quarter or year to reflect the latest information.

**Comment by awpala** [comment]
I like the idea of a real-time dashboard, but depends how complex it would be to implement such a thing...I think the bottleneck will be dealing with disparate funding sources and whether or not they have easy APIs/integrations to use for that purpose, but otherwise something like a "progress bar" or similar would be trivial to implement from a UI standpoint and a great "transparency" metric for the community.

**Comment by driscoll42** [comment]
I would think that for the MVP , this could simply be posting the bill from AWS or whatever service every month or so for the initial phase and then possibly a bar like this. Non-Profits are only required to submit financial reports publicly annually and anymore more is just icing on the cake. While I love the idea of a progress bar/real time updates, that feels like a 2.0/3.0 feature.

**Comment by keithhenning** [comment]
I assumed I would be opening a bank account for the organization once the charter is done and I have a tax ID, which will take a few weeks. I will also take care of the first annual report, but then let someone else take care of year 2. Where would we like the bank account set up? An internet bank or national bank, such as BoA or Chase? Just let me know. I will be knocking most of this out the beginning of next week.

**Comment by knakamura13** [comment]
Assuming you create a new bank account with BofA, for example, will we be able to transfer ownership to someone else in the future?

**Comment by keithhenning** [comment]
The account would be under the name of the organization with nominated members with access. Those can be changed out at any time with a notarized memo from the organization

**Comment by MatthewCaseres** [comment]
https://opencollective.com/

This is an open source collective that I set up - https://opencollective.com/actuarial-open-source.

**Comment by MatthewCaseres** [comment]
I heard on discord that there is a nonprofit being set up? Maybe this is a good option - https://opencollective.com/foundation

**Comment by awpala** [comment]
Closing as stale (i.e., lack of interest, ability to develop with current-to-long-term resources, etc.). Please reopen with appropriate justification if still relevant.
