### ISSUE TITLE
[FEATURE] Make website analytics visible

### ISSUE THREAD

**Issue by driscoll42** [omshub/website#27]
**Is your feature request related to a problem? Please describe.**
Not a problem, but it would be interesting to make details on the website visible.

**Describe the solution you'd like**
By that I would mean seeing how many people visited each month, which courses were most viewed, etc... I'm not fully certain what is possible, but the more transparency the better. Here's some [reddit stats](https://imgur.com/a/JYD92) that are similar to what I had in mind, or ones from Google Analytics.

**Comment by MatthewCaseres** [comment]
Yeah we need Google Analytics.

**Comment by awpala** [comment]
Closing as stale (i.e., lack of interest, ability to develop with current-to-long-term resources, etc.). Please reopen with appropriate justification if still relevant.
