### ISSUE TITLE
[FEATURE] Create Course Maps for the specializations/tracks

### ISSUE THREAD

**Issue by driscoll42** [omshub/website#30]
**Is your feature request related to a problem? Please describe.**
UT Austin has some fantastic course maps: https://mscshub.com/courseMap It'd be great to have similar

**Describe the solution you'd like**
Would probably be best to make one per specialization, and to basically copy what they did, I made a sample of a rough draft of a ML spec one below. Would need some community help to figure out how it should look for all the various specializations/tracks/courses. Further how/should non-spec/track courses be included? 

**Additional context**
![image](https://user-images.githubusercontent.com/4751505/167754680-6484f04f-86bd-4189-aff5-92709bd21828.png)

**Comment by disposedtrolley** [comment]
Wow those look fantastic! We could look into using [Mermaid JS](https://mermaid-js.github.io/mermaid/#/) to render our diagrams programmatically.

**Comment by knakamura13** [comment]
Wowww Mermaid JS is such a cool idea. I’m down to move forward with that library.

I don’t know how important this issue is for our MVP, though.

**Comment by awpala** [comment]
Closing as stale (i.e., lack of interest, ability to develop with current-to-long-term resources, etc.). Please reopen with appropriate justification if still relevant.
