### ISSUE TITLE
[ADMINISTRATIVE] Obtain branding permission from Gatech licensing office

### ISSUE THREAD

**Issue by premk** [omshub/website#31]
Non-profits are allowed to use Georgia Tech branding provided they obtain permission from the licensing office. 

https://licensing.gatech.edu/off-campus/non-profit

This should be done once we close #9 and have an MVP.

**Comment by awpala** [comment]
Closing as stale (i.e., lack of interest, ability to develop with current-to-long-term resources, etc.). Please reopen with appropriate justification if still relevant.
