### ISSUE TITLE
[FEATURE] Additional course metrics

### ISSUE THREAD

**Issue by premk** [omshub/website#32]
**Is your feature request related to a problem? Please describe.**
OMSCentral displayed a simple arithmetic mean for all available metrics (workload, rating, difficulty etc). This may be misleading as course syllabus, instructing team and logistics change over time.

**Describe the solution you'd like**
Keep the overall metrics and display additional data only for the last two semesters (or a reasonable lower bound). 

**Describe alternatives you've considered**
Display a graph of the metrics over time (similar to steam ratings).

**Comment by driscoll42** [comment]
I was thinking perhaps a weighted average of the past three semesters, but overall I agree. Something to keep in mind is that summer semesters will be somewhat different than Fall/Spring, both due to a condensed/removed content and fewer people reviewing.

**Comment by CBlumini** [comment]
As a first past though weighting the most recent 2-3 semester high makes sense to me. 1x, 0.8, 0.6 until they fall off? How useful is 4 year old data from a prediction standpoint? The school does some of the scaling for us by taking stuff out of certain summer courses. Classes with really bad summers would be picked up by reading text reviews or potentially a word cloud if that becomes a thing.  

Alternatively:

Maybe it makes sense to use some sort of forecasting model where we take into account the cyclic nature of the year? The actual data sets are fairly small so it doesn't strike me as too computationally intensive. You'd only need to run the calc when a new review is submitted.

**Comment by awpala** [comment]
Closing as stale (i.e., lack of interest, ability to develop with current-to-long-term resources, etc.). Please reopen with appropriate justification if still relevant.
