### ISSUE TITLE
[FEATURE] Course Review Search

### ISSUE THREAD

**Issue by adamwespiser** [omshub/website#34]
**Is your feature request related to a problem? Please describe.**
There should be a way for our end users to search over the collection of reviews for a specific course.

**Describe the solution you'd like**
On a per course basis, there will be a "search" menu on each page, where in the user enters a string, and we narrow the results returned to only include those reviews that have a match.
It's also possible to "fully feature" this, and add additional filters, like date ranges, filter by ratings, hours, difficulty, et cetera which will be marginally extra effort for a lot more utility.

This will allow our end users to ask questions like: "what did my fellow OMSCSers think of the final in ESO?", or "Maybe distributed computing isn't that hard, what do the positive reviews say?", or "what do the old timers think of Computational Journalism". 

**Describe alternatives you've considered**
I am proposing that we implement search as a server based feature that queries the database and directly returns the results. It's also possible to make a site's search work via a third party service, like ElasticSearch. However, I don't think we'll need this level of sophistication/complexity given that our search domain is homogenous (course reviews) and the number of reviews per course pretty low.

**Comment by awpala** [comment]
This is a really good idea!

**Comment by awpala** [comment]
Closing for feasibility. This will be difficult to implement with our currently chosen/implemented Firebase backend and would require a managed backend to implement such full-text search properly.
