### ISSUE TITLE
[FEATURE] Add email to website & README

### ISSUE THREAD

**Issue by awpala** [omshub/website#351]
**Is your feature request related to a problem? Please describe.**
Currently, there is no public visibility to the group email contact.

**Describe the solution you'd like**
Add an email icon to the navbar linking to `gt.omshub@gmail.com`, as well as corresponding entry near the top of `README.md`

**Describe alternatives you've considered**
(N/A)

**Additional context**
(N/A)

**Comment by Udassi-Pawan** [comment]
I would like to work on this issue, would you assign it to me?

**Comment by awpala** [comment]
@Udassi-Pawan please feel free to self-assign, we're not super strict here in general with formalities / "parliamentary procedures"...furthermore, there should be no restrictions set against PR'ing from forked branches, either.

However, if you do run into issues with self-assign and/or PR'ing, please let me know so I can resolve accordingly. Thanks!
