### ISSUE TITLE
[FEATURE] Configure Vercel with Terraform

### ISSUE THREAD

**Issue by disposedtrolley** [omshub/website#37]
We should consider using Terraform to configure our Vercel resources (project, custom domain, and deployments). This gives us a repeatable way to deploy our infrastructure, and acts as a form of documentation. The Terraform code can live in a separate `ops` repo or similar.

Links:

- [Vercal Terraform provider](https://registry.terraform.io/providers/vercel/vercel/latest)

**Comment by driscoll42** [comment]
@disposedtrolley Do you think is more of a MVP, 2.0, or Future feature?

**Comment by disposedtrolley** [comment]
@driscoll42 MVP I reckon. Getting infrastructure automation established will free us up for user-facing feature work.

**Comment by DevSecNinja** [comment]
+1 for Terraform

**Comment by MatthewCaseres** [comment]
Vercel account configurations are very simple, this is not necessary at all. Using Vercel to build a web app is nothing like using some cloud provider. 

Please close this.

**Comment by awpala** [comment]
Closing as stale (i.e., lack of interest, ability to develop with current-to-long-term resources, etc.). Please reopen with appropriate justification if still relevant.
