### ISSUE TITLE
[FEATURE] Include CIOS Data

### ISSUE THREAD

**Issue by premk** [omshub/website#4]

**Comment by driscoll42** [comment]
Including some more details

Pull in [CIOS](https://academiceffectiveness.gatech.edu/surveys/cios/accessing-cios-and-survey-results) data similar to [critique.gatech.edu](http://critique.gatech.edu/), here's the [Github repo](https://github.com/GT-SGA/Course-Critique) for it, there may be a way to do with public APIs

**Comment by awpala** [comment]
I think we should determine the use case for this first, and similarly for the LITE data. The main thing we should avoid is recreating a new dashboard just to summarize the same data; the respective official sites are already doing that...

**Comment by driscoll42** [comment]
True, true, though having one central repository for this data I think would be helpful. However I figure this is a "Future" issue so I set it for that milestone, not even a "2.0" release. One step at a time.

**Comment by awpala** [comment]
I think the main insight would be comparing survey data from "official sources" vs. reporting "freely" via the platform; as for the value prop, that remains to be determined...

**Comment by driscoll42** [comment]
![image](https://user-images.githubusercontent.com/4751505/167754422-2e8b94a4-8439-4c3f-a436-ce681a3f08dc.png)
![image](https://user-images.githubusercontent.com/4751505/167754428-7e173c77-2c48-42ee-b551-0c8cc3b00519.png)
![image](https://user-images.githubusercontent.com/4751505/167754435-e17086a1-fbc0-4ed9-99fe-ad8065d44206.png)
![image](https://user-images.githubusercontent.com/4751505/167754441-93bb1665-d0b8-495e-861f-9714715fdc5a.png)

- In general, OMSCentral's hours are 15% more than CIOS, though MGT courses are the exception with OMSCentral hours being less than CIOS for 5 of 7
- CIOS Course effectiveness... might be a bit useless, or people just find things all sorts of difficult but still effective
- No relation between OMSCentral difficulty and rating, but a loose one between rating and assignments measuring knowledge

So I did some comparison before which I did think was interesting.

**Comment by awpala** [comment]
Closing as stale (i.e., lack of interest, ability to develop with current-to-long-term resources, etc.). Please reopen with appropriate justification if still relevant.
