### ISSUE TITLE
[FEATURE] New Logo

### ISSUE THREAD

**Issue by driscoll42** [omshub/website#41]
Currently there is no logo for OMSHub and one would be needed for branding purposes. Note we cann0t use Buzz from GA Tech

**Comment by awpala** [comment]
I'm not too hung up on getting Buzz to work, personally, I think our effort/energy is better spent elsewhere at this point, especially if they have a knack for sour grapes over its usage...

**Comment by driscoll42** [comment]
True, this is probably more of a "nice to have" than MVP. I'll make it for 2.0 instead

**Comment by knakamura13** [comment]
I made a little logo and favicon. Not sure if anyone else likes it but it'll do until a real designer can have a go at a logo for OMSHub.

![omshub-favicon](https://user-images.githubusercontent.com/20162718/168055047-1740a2b7-8fe3-448f-a07f-829fe95a7685.png)
![omshub-logo-variation-1-v1](https://user-images.githubusercontent.com/20162718/168055049-ee7dd08e-3fa0-4491-a2ad-ef1257dcef31.png)

**Comment by knakamura13** [comment]
If 2 or 3 people say they are okay with this logo (at least for the short-term future), let's close this issue as "done."

**Comment by csc5nz** [comment]
Just an idea for a logo. 

![logo_hd_color_02_c](https://user-images.githubusercontent.com/31320108/168411430-cbac75e6-50e5-47c4-a773-8c637965aa6f.jpg)

**Comment by knakamura13** [comment]
Here’s my personal favorite logo that I’ve designed so far:

![9F2180A5-25ED-440F-921E-AE363D72954D](https://user-images.githubusercontent.com/20162718/168808250-e6e9d4b7-e026-4ace-addc-bf0830cda794.jpeg)

**Comment by driscoll42** [comment]
I like that one a lot, The Blue and Gold is pretty. If the logo were much bigger, having a star or something on Atlanta would be fun, but too small for that.

**Comment by knakamura13** [comment]
We could replace the globe with a glyph that look like Georgia :P
