### ISSUE TITLE
[FEATURE] Components Library / Design System

### ISSUE THREAD

**Issue by awpala** [omshub/website#42]
Build out key critical components using MUI for use throughout the application

**Comment by knakamura13** [comment]
I'm volunteering @herman-rogers for this task following [our discussion on Slack](https://omscs-study.slack.com/archives/C03EQ7X7KLJ/p1652293609898299?thread_ts=1652292985.637479&cid=C03EQ7X7KLJ). If he isn't willing to take on this task in the next week, I'll have a go at it myself.

**Comment by charlesgoh** [comment]
[I've tweaked a Navbar a little to automate the generation of Links. Do let me know your thoughts.](https://github.com/omshub/website/pull/71)
