### ISSUE TITLE
[FEATURE] OMS Resources/Guides

### ISSUE THREAD

**Issue by driscoll42** [omshub/website#45]
In order to make the website more useful for students, resources/guides could be added to the site to help future students. Such things could include "How to do research" "how to prepare for classes" and similar. Though this could be similar to some of what is on wikidot, omsa.ga/omscs.ga so there would need to be a means of not overlapping, and augmenting.

**Comment by awpala** [comment]
Closing as stale (i.e., lack of interest, ability to develop with current-to-long-term resources, etc.). Please reopen with appropriate justification if still relevant.
