### ISSUE TITLE
[ADMINISTRATIVE] Decide on a Git workflow for pushing changes to production

### ISSUE THREAD

**Issue by disposedtrolley** [omshub/website#48]
We currently have two integration branches:

- `dev` which deploys to [dev.omshub.org](http://dev.omshub.org/)
- `main` which deploys to [omshub.org](http://omshub.org/)

The repository is configured with `dev` as the default branch. This means that when a PR is merged, it will deploy into a "development" version of the site. An additional PR needs to be created to merge the `dev` branch into `main` to deploy to the production site. This method is sometimes known as Gitflow and is one of two commonly used Git workflows, with the alternative being [trunk-based development])(https://www.atlassian.com/continuous-delivery/continuous-integration/trunk-based-development).

We should decide if we want to adopt trunk-based development or stick with the Gitflow-style model we currently have. **I am biased towards the former, but I'm also more than happy to back Gitflow if that's the decision of the community -- this is our project, so we should all have a say.**

Trunk-based development has the following advantages:

- A single integration branch. When a change is approved and merged, it's on the way to production. This forces us to be disciplined in opening small PRs and giving thorough reviews. Small changes are also easier to test, and in the worst case, revert.
- No overhead in deciding on a release cadence. Releases happen when a PR is approved.
- No overhead in synchronising changes between integration branches. A single branch represents the code that's externally visible to users.
- Vercel deploys a live preview site for each PR we create (you can see an [example here](https://github.com/omshub/website/pull/47#issuecomment-1124651047)). This removes the need for a dedicated integration branch like `dev` for previewing changes. My philosophy with dev environments in general is that they should be ephemeral; created when needed and destroyed when irrelevant.
- Ownership. The author of a PR can be responsible for the entire lifecycle of their change; from inception to deployment.

Where trunk-based development falls short is long-lived dev or test environments, particularly for user testing (these are great points made in the Slack thread below). My counter to this is that we should make small PRs (changing one component at a time), or spin off an ad-hoc integration branch when it’s warranted (if we’re doing a big redesign consisting of a large collection of PRs). Ad-hoc integration branches work nicely for user testing too; we can cherry pick the relevant commits into a branch that’s named after the purpose of the test.

I really want to optimise our Git workflow for the common case, which is regularly deploying small changes into production.

## Links

- [Slack discussion](https://omscs-study.slack.com/archives/C03EQ7X7KLJ/p1652224365489389)

**Comment by knakamura13** [comment]
I think I'm on board with the idea of deleting `dev` and using `master` as the sole deployment target. Using Vercel's live previews for each pull request will make testing easier and, again, remove the need for an additional development branch.

I say we move forward with this idea.

**Comment by disposedtrolley** [comment]
Should we go ahead and switch the default branch back to main?

**Comment by disposedtrolley** [comment]
I've prepared https://github.com/omshub/website/pull/58 to merge dev into main when we're ready!
