### ISSUE TITLE
[ADMINISTRATIVE] Auto-delete branches after merge

### ISSUE THREAD

**Issue by disposedtrolley** [omshub/website#49]
Should we enable the option to [automatically delete branches](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches) after its associated PR has been merged?

This helps keeps our branch list clean, and is not a destructive operation (we can always restore deleted branches).

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/4476568/168032410-220999a4-881d-4418-bf22-ea70897b568f.png">

**Comment by knakamura13** [comment]
Probably a good idea. +1 from me.

**Comment by disposedtrolley** [comment]
Done! We can always change it back if we're not happy.

**Comment by awpala** [comment]
No objections here, nothing worse than coming back in a month with a bunch of zombie feature branches lingering around in the repo lol
