### ISSUE TITLE
[FEATURE] Include LITE Grade Distribution Data

### ISSUE THREAD

**Issue by premk** [omshub/website#5]

**Comment by adamwespiser** [comment]
does LITE provide a public API, or can it? Last time I was on it required me to login in via 2FA to get the data.
Not the end of the world, but there would be a manual step every semester to update the information.

**Comment by baheckman** [comment]
Maybe to start, we could just link to LITE for each course and further discuss if/how we can use LITE data sometime further down the road.

**Comment by premk** [comment]
I think this is a very useful metric. 

For example, Distributed Computing gets a very bad rep because of the harsh reviews, perceived difficulty and effort/week metric in OMSCentral. 
But the data in CIOS and LITE says otherwise, the drop rate is about 25% which is much less than GIOS or HPCA, the required effort according to CIOS is about 20 hours/week and about 40% of the class gets an A. This is a reasonably difficult course for a Gatech grad student. 

If I was a new student planning out my courses based solely on OMSCentral data, I would be scared away from even considering DC.

**Comment by premk** [comment]
> I would be hesitant to get data that is behind GA Tech's 2FA login to make public without consulting with Georgia Tech first. That's a potential "Shut down or we sue" kind of thing they could go for.

Grade Distribution report is public access and doesn't require login. It is just an embedded tableau report, I am unsure if there is a public API.

**Comment by awpala** [comment]
Closing as stale (i.e., lack of interest, ability to develop with current-to-long-term resources, etc.). Please reopen with appropriate justification if still relevant.
