### ISSUE TITLE
[FEATURE] Expand scope of site to include on campus students/reviews

### ISSUE THREAD

**Issue by driscoll42** [omshub/website#53]
**Is your feature request related to a problem? Please describe.**
There is no specific reason why the site could not be used by on campus undergrad and graduate students and one expects it would be useful to them as well. However it would dramatically increase the scope of the project and we would need contacts on campus to make it happen.

**Additional context**
Not MVP or even 2022 goal I think, but worth keeping in mind.

**Comment by awpala** [comment]
Closing as stale (i.e., lack of interest, ability to develop with current-to-long-term resources, etc.). Please reopen with appropriate justification if still relevant.
