### ISSUE TITLE
[FEATURE] Create a Job Board

### ISSUE THREAD

**Issue by driscoll42** [omshub/website#54]
**Is your feature request related to a problem? Please describe.**
A review site would be seen by a number of recruiters, users, etc... and having a job board could allow for them to advertise positions at their company. In theory it could allow for the site to be self-funding without requiring donations.

**Additional context**
This would be fraught with all sorts of potential issues, how to post, how to charge, if to charge, etc... This should be discussed, but not until later.

**Comment by awpala** [comment]
Leaving open for relevance, however, stating for record as of Aug 2022 that this is unlikely to be completed due to lack of resources / dedicated personnel. Based on current progress trajectory, scope of this project will be limited primarily to reviews functionality only for the time being.

**Comment by awpala** [comment]
Closing as stale (i.e., lack of interest, ability to develop with current-to-long-term resources, etc.). Please reopen with appropriate justification if still relevant.
