### ISSUE TITLE
[FEATURE] Allow for the site to be used for OMS degrees offered other than GA Tech

### ISSUE THREAD

**Issue by driscoll42** [omshub/website#60]
**Is your feature request related to a problem? Please describe.**
It is a bit presumptuous to call us OMSHub as that just means "Online Masters in Science Hub" so kind of implying all other online masters in science are applicable, but definitely we don't mean that at the moment.

**Describe the solution you'd like**
Have a landing page where you pick your university and directs you to gatech.omshub.com or uiuc.omshub.com or utexas.omshub.com, etc... 

**Additional context**
This is very much not a MVP feature and likely not a feature we will ever implement, but it is worthy of discussion and consideration.

**Comment by driscoll42** [comment]
In theory could be for non-Masters degreess OBSHub, OASHub, etc...

**Comment by awpala** [comment]
Closing as stale (i.e., lack of interest, ability to develop with current-to-long-term resources, etc.). Please reopen with appropriate justification if still relevant.
