### ISSUE TITLE
[FEATURE] Determine License

### ISSUE THREAD

**Issue by driscoll42** [omshub/website#64]
**Is your feature request related to a problem? Please describe.**
There are many possible licenses to use for this project, MIT, GPLv3, etc... we need to pick one - https://choosealicense.com/

**Comment by premk** [comment]
We should go with a permissive copy left license. AGPL 3.0?

**Comment by knakamura13** [comment]
I like [GNU AGPLv3](https://choosealicense.com/licenses/agpl-3.0/) a lot!

**Comment by knakamura13** [comment]
Shall we agree to move forward with AGPLv3 or does anyone want to wait for more feedback from the community?

I’m assuming we can downgrade the license to MIT later if we want to, right? (Or is a license permanently attached to the code it pertains to?)

**Comment by keithhenning** [comment]
My legal recommendation last week was for https://www.gnu.org/licenses/gpl-3.0.en.html

**Comment by knakamura13** [comment]
Oh, my bad, Keith. If that's your recommendation then I am okay with changing the license.

**Comment by knakamura13** [comment]
> My legal recommendation last week was for https://www.gnu.org/licenses/gpl-3.0.en.html

I changed the license to GPLv3, which I believe is totally okay to do because we haven't "released" any of our code yet.

**Comment by driscoll42** [comment]
Honestly I thought GPLv3 and AGPLv3 were the same thing, but apparently not

**Comment by keithhenning** [comment]
They are slightly different. We will have an easier time of things using GPLv3.

**Comment by knakamura13** [comment]
Understood, thanks for your recommendation Keith.

Everyone okay with closing out this ticket now? We still need to add License information to the following locations:
- README
- About page on the website
