### ISSUE TITLE
[FEATURE] Automate making changes to the OMS curriculum (courses, specializations, tracks, etc...)

### ISSUE THREAD

**Issue by ilanbarshir** [omshub/website#67]
**Is your feature request related to a problem? Please describe.**
Keep site data up-to-date

**Describe the solution you'd like**
Web scraping the data, clean and insert into relevant tables in db. Scrape both omscs official site and omscentral on a daily basis, clean and normalize the data, then update relevant tables.

**Describe alternatives you've considered**
ools to consider here are python scrapy for scraping data, and python pandas to normalize and clean it. Some relevant tables also should be added to the DB 

**Additional context**
The data should be extracted into an 'offline' db, so in case of an error in scraping the data of the site is not deleted. Maybe more thinking should be taken into account how the data is being passed from the 'offline' db into the production one

**Comment by awpala** [comment]
Closing as stale (i.e., lack of interest, ability to develop with current-to-long-term resources, etc.). Please reopen with appropriate justification if still relevant.
