### ISSUE TITLE
[FEATURE] FAQ page

### ISSUE THREAD

**Issue by premk** [omshub/website#69]
**Is your feature request related to a problem? Please describe.**
New students usually ask the same questions every semester in Reddit and Slack. 

**Describe the solution you'd like**
Add an FAQ page with well written answers to common questions from other sources and provide attribution.

**Comment by awpala** [comment]
Closing as stale (i.e., lack of interest, ability to develop with current-to-long-term resources, etc.). Please reopen with appropriate justification if still relevant.
