### ISSUE TITLE
[BUG] Website is down

### ISSUE THREAD

**Issue by pmesgari** [omshub/website#74]
**Describe the bug**
When navigating to the URL https://omscentral.com/ the page below displayed instead of the usual home page with the courses.

![image](https://user-images.githubusercontent.com/14719521/168678734-76d9b704-0c4f-438f-b589-ec862ac5395a.png)

**To Reproduce**
Navigate to the website

**Comment by ctran4347** [comment]
You are looking at the wrong website. The website related to this repo is https://omshub.org/. Omscentral is another site **owned** by someone else
