### ISSUE TITLE
[ADMINSTRATIVE] Administrivia

### ISSUE THREAD

**Issue by awpala** [omshub/website#8]
Determine centralized ownership:
- Services accounts (frontend & backend)
- Email (general gmail or similar vs. gatech.edu domain)
- License & Terms of Service, Data Policy, etc.
- Ownership: Individual vs. LLC vs. 501(c) etc.

**Comment by premk** [comment]
Regarding email, I recommend a distribution group or a mail enabled security group where members can be added and removed as they graduate. Members of this group would just be the people in the charter Keith is drawing up. 

This avoids password sharing and a whole host of problems that comes along with it.

**Comment by disposedtrolley** [comment]
> Services accounts (frontend & backend)

How is our Vercel account set up currently?

**Comment by driscoll42** [comment]
I think we might be able to close this ticket:


    Services accounts (frontend & backend)
        - #7
    Email (general gmail or similar vs. gatech.edu domain)
        - Kind of covered by #9 as servicing emails and #33 for user auth
    License & Terms of Service, Data Policy, etc.
        - ToS: #23 
        - Data Governance #28 
        - License #64
    Ownership: Individual vs. LLC vs. 501(c) etc.
       - Basically covered by #9

**Comment by awpala** [comment]
Agreed with the move to close/redirect, I mostly opened this issue initially in a "putting down thoughts while fresh" episode, good call!
