### ISSUE TITLE
[FEATURE] Tying classes to instructor of record

### ISSUE THREAD

**Issue by driscoll42** [omshub/website#85]
**Is your feature request related to a problem? Please describe.**
please consider a tying classes to the instructor of record. There will come a time in which there may be multiple versions of classes taught by multiple professors, and it might be nice for the data structure in the backend to be able to easily accommodate this feature? (I don't know - this is not my forte)

Suggested by Kai

**Comment by awpala** [comment]
Closing as stale (i.e., lack of interest, ability to develop with current-to-long-term resources, etc.). Please reopen with appropriate justification if still relevant.
