### ISSUE TITLE
[FEATURE] Add Course Rubrics

### ISSUE THREAD

**Issue by driscoll42** [omshub/website#86]
**Is your feature request related to a problem? Please describe.**
I believe rubrics are a critical feature for students, especially for classes that have rubrics behind sso logins. 

--Suggested by Kai

**Comment by westim** [comment]
This could add a lot of maintenance burden to keep syllabi relatively up-to-date for every class.

OMSCS classes keep recent syllabi linked on the corresponding [course pages](https://omscs.gatech.edu/current-courses). The potential benefit is minimal beyond what is already provided.

**Comment by awpala** [comment]
> This could add a lot of maintenance burden to keep syllabi relatively up-to-date for every class.
> 
> OMSCS classes keep recent syllabi linked on the corresponding [course pages](https://omscs.gatech.edu/current-courses). The potential benefit is minimal beyond what is already provided.

This is my general thinking for this issue, as well...I could see perhaps the one upside being a one-stop-shop that also serves as a proxy archive/depot over time, on the off chance somebody lost track of theirs and wanted to stroll down memory lane(?). But agreed probably a reach, and definitely not a high priority, at that.

**Comment by awpala** [comment]
Closing as stale (i.e., lack of interest, ability to develop with current-to-long-term resources, etc.). Please reopen with appropriate justification if still relevant.
