### ISSUE TITLE
[BUG] Use Static Site Generation to generate review pages

### ISSUE THREAD

**Issue by MatthewCaseres** [omshub/website#99]
**Describe the bug**
We are currently fetching data in a useEffect, it can be generated at build time.

**To Reproduce**
There is a loading spinner that shouldn't exist when looking at the course reviews.

**Expected behavior**
Pages are **blazingly fast**.

**Comment by MatthewCaseres** [comment]
https://nextjs.org/docs/basic-features/data-fetching/get-static-props

**Comment by shaun-jacks** [comment]
I'm new to Next but was curious what happens if the review data changes after build time? Do we need to do another rebuild of the site? Then I came across https://youtu.be/BGexHR1tuOA and this seems to fix that !

**Comment by MatthewCaseres** [comment]
Right! I have it in this branch for the main page, just waiting on merge

https://github.com/omshub/website/pull/100

**Comment by awpala** [comment]
Using [SWR](https://swr.vercel.app/) instead for data fetching, cf. PR #131. Closing issue.
